[dependencies]
base = "https://github.com/serokell/motoko-base#$TEST_BRANCH"
base-unopt = "https://github.com/serokell/motoko-base#$BASELINE_BRANCH"
stableheapbtreemap = "1.3.0"
map = "9.0.0"
splay = "0.1.0"
vector = "0.2.0"
